### ISSUE TITLE
use conflicts_with

### ISSUE THREAD

**Issue by awsomearvinder** [fishappy0/pigrabbit-cli#6]
This will lead to a cleaner API overall instead of you e.g. panicing in execute_command if both id and record type are passed.

**Comment by awsomearvinder** [comment]
I think you could also use this to merge together `EditOptions` and `DeleteOptions`, so you can use a single struct for that instead of a SubCommand, which might look nicer on the CLI.

**Comment by fishappy0** [comment]
> I think you could also use this to merge together `EditOptions` and `DeleteOptions`, so you can use a single struct for that instead of a SubCommand, which might look nicer on the CLI.

I don't think they should be merged since their content is different.

**Comment by fishappy0** [comment]
Fixed #6!
